### ISSUE TITLE
Create a Layout for the Flash Cards

### ISSUE THREAD

**Issue by sebuzz** [sebuzz/capstone#4]
As a User,
I need a Card to display the vocabulary,
to be able to learn / test myself.

#### Acceptance Criteria:

- [ ] User should be able to flip the Cards
- [ ] The Vocab Word should be directly visible

#### Tasks:
- [ ] add a Title
- [ ] add method to flip Card
- [ ] add fields to display front side content
- [ ] add fields to display backside content
- [ ] add method to mark as favourite
- [ ] add method to mark as 
       correct / wrong answer.
- [ ] add a basic Layout
- [ ] add a basic styling
